mainapp/urls.py
from django.urls import path

from .views import index, back_up

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('backup/', back_up, name='backup'),
]

storageCRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('todo/', include('todoapp.urls', namespace='todoapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('partners/', include('partnersapp.urls', namespace='partnersapp')),
    path('storage/', include('storageapp.urls', namespace='storageapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('transport/', include('transportapp.urls', namespace='transportapp')),
    path('accounts/', include('django.contrib.auth.urls')),
]

storageapp/urls.py
from django.urls import path

from .views import product_list, ProductDetailView, ProductByCategoryListView, ProductCreateView, ProductUpdateView, \
    product_active, NomenCreateView, NomenUpdateView, NomenDetailView, roll_to_retail, TkCreateView, BatchCreateView, \
    CategoryCreateView

app_name = 'storageapp'

urlpatterns = [
    path('', product_list, name='index'),

    path('product/create/<int:pk>', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<slug:slug>', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<slug:slug>', product_active, name='active'),
    path('product/detail/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/to-retail/<slug:slug>/', roll_to_retail, name='roll_to_retail'),

    path('nomen/detail/<slug:slug>/', NomenDetailView.as_view(), name='nomen_detail'),
    path('nomen/create/', NomenCreateView.as_view(), name='nomen_create'),
    path('nomen/update/<slug:slug>', NomenUpdateView.as_view(), name='nomen_update'),

    path('category/<slug:slug>', ProductByCategoryListView.as_view(), name='by_category'),

    path('tk_create/', TkCreateView.as_view(), name='tk_create'),
    path('batch_create/', BatchCreateView.as_view(), name='batch_create'),
    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
]

storageapp/forms.py
from django import forms

from ordersapp.models import TKList
from .models import ProductList, NomenList, BatchList, CategoryList


class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductList
        exclude = ('slug', 'is_active', 'name')


class TkCreateViewForm(forms.ModelForm):
    class Meta:
        model = TKList
        exclude = ('pk', )

    def __init__(self, *args, **kwargs):
        super(TkCreateViewForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class BatchCreateViewForm(forms.ModelForm):
    class Meta:
        model = BatchList
        exclude = ('slug', )

    def __init__(self, *args, **kwargs):
        super(BatchCreateViewForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class CategoryCreateViewForm(forms.ModelForm):
    class Meta:
        model = CategoryList
        exclude = ('slug', )

    def __init__(self, *args, **kwargs):
        super(CategoryCreateViewForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class NomenForm(forms.ModelForm):
    class Meta:
        model = NomenList
        exclude = ('slug', 'is_active')

    def __init__(self, *args, **kwargs):
        super(NomenForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class SearchForm(forms.Form):
    pass

storageapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from ordersapp.models import TKList
from .forms import ProductForm, NomenForm, SearchForm, TkCreateViewForm, BatchCreateViewForm, CategoryCreateViewForm
from .models import ProductList, CategoryList, NomenList, BatchList


@login_required
def product_list(request):
    objects = NomenList.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)

        if form.is_valid():
            search_results = []
            data_for_search = form.data['data_for_search']

            if data_for_search.isdigit():
                search_results = list(NomenList.objects.filter(pk=int(data_for_search)))

            search_results = set(list(NomenList.objects.filter(part_number__contains=data_for_search)) + \
                                 list(NomenList.objects.filter(name__contains=data_for_search)) + \
                                 search_results)

            context = {
                'title': 'Товары',
                'objects': search_results,
                'category_links': CategoryList.objects.all(),
                'products_count': ProductList.get_all_products_amount(),
                'dfs': data_for_search,
            }
            return render(request, 'storageapp/index.html', context)

    context = {
        'title': 'Товары',
        'objects': objects,
        'category_links': CategoryList.objects.all(),
        'products_count': ProductList.get_all_products_amount(),
    }

    return render(request, 'storageapp/index.html', context)


class ProductByCategoryListView(LoginRequiredMixin, ListView):
    model = NomenList
    template_name = 'storageapp/index.html'
    context_object_name = 'objects'

    def get_queryset(self):
        qs = NomenList.objects.all()
        if self.kwargs['slug'] is not None:
            category = get_object_or_404(CategoryList, slug=self.kwargs['slug'])
            qs = self.model.objects.filter(category=category.pk)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductByCategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Товары'
        context['category_links'] = CategoryList.objects.all()
        context['products_count'] = ProductList.get_all_products_amount()
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = ProductList
    template_name = 'storageapp/product_detail.html'
    context_object_name = 'object'

    def get_queryset(self):
        return ProductList.objects.filter(is_active=True)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = ProductList
    template_name = 'storageapp/product_create_form.html'
    context_object_name = 'product_objects'
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Добавить товар'
        return context

    def form_valid(self, form):
        nomen = NomenList.objects.get(pk=self.kwargs['pk'])
        self.object = form.save(commit=False)
        self.object.name = nomen
        self.object.save()

        return HttpResponseRedirect(
            reverse(
                'storageapp:nomen_detail',
                kwargs={'slug': nomen.slug}))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = ProductList
    form_class = ProductForm
    template_name = 'storageapp/product_crud_form.html'
    success_url = reverse_lazy('storageapp:index')

    def get_success_url(self):
        product_slug = self.kwargs['slug']
        nomen = NomenList.objects.get(product__slug=product_slug)
        return reverse('storageapp:nomen_detail', kwargs={'slug': nomen.slug})

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирования товара'
        context['obj'] = ProductList.objects.get(slug=self.kwargs['slug'])
        return context


@login_required
def product_active(request, slug):
    product = get_object_or_404(ProductList, slug=slug)
    prod_slug = NomenList.objects.get(product__slug=slug).slug

    if request.method == 'GET':
        if product.is_active:
            product.is_active = False
        else:
            product.is_active = True

        product.save()

        return HttpResponseRedirect(reverse('storageapp:nomen_detail', kwargs={'slug': prod_slug}))


@login_required
def roll_to_retail(request, slug):
    product = get_object_or_404(ProductList, slug=slug)
    prod_slug = NomenList.objects.get(product__slug=slug).slug

    if request.method == 'GET':
        product.amount = product.amount - 1
        product.save()

        new_ret = ProductList(
            name=product.name,
            batch=product.batch,
            is_active=True,
            is_retail=True,
            amount=NomenList.objects.get(product__slug=slug).meters
            )

        new_ret.save()

        return HttpResponseRedirect(
            reverse(
                'storageapp:nomen_detail',
                kwargs={
                    'slug': prod_slug}))


class NomenCreateView(LoginRequiredMixin, CreateView):
    model = NomenList
    template_name = 'storageapp/product_create_form.html'
    context_object_name = 'nomen_objects'
    form_class = NomenForm

    def get_context_data(self, **kwargs):
        context = super(NomenCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Добавить номенклатуру'
        return context


class NomenUpdateView(LoginRequiredMixin, UpdateView):
    model = NomenList
    form_class = NomenForm
    template_name = 'storageapp/product_crud_form.html'
    success_url = reverse_lazy('storageapp:index')

    def get_context_data(self, **kwargs):
        context = super(NomenUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирования номенклатуры'
        context['obj'] = NomenList.objects.get(slug=self.kwargs['slug'])
        return context


class NomenDetailView(LoginRequiredMixin, DetailView):
    model = NomenList
    template_name = 'storageapp/nomen_detail.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super(NomenDetailView, self).get_context_data(**kwargs)
        context['retail'] = ProductList.objects.filter(name=self.object, is_retail=True, is_active=True)
        return context


class TkCreateView(LoginRequiredMixin, CreateView):
    model = TKList
    template_name = 'storageapp/product_crud_form.html'
    context_object_name = 'nomen_objects'
    form_class = TkCreateViewForm
    success_url = reverse_lazy('storageapp:index')

    def get_context_data(self, **kwargs):
        context = super(TkCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Добавить Транспортную'
        return context


class BatchCreateView(LoginRequiredMixin, CreateView):
    model = BatchList
    template_name = 'storageapp/product_crud_form.html'
    context_object_name = 'nomen_objects'
    form_class = BatchCreateViewForm
    success_url = reverse_lazy('storageapp:index')

    def get_context_data(self, **kwargs):
        context = super(BatchCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Добавить партию'
        return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = CategoryList
    template_name = 'storageapp/product_crud_form.html'
    context_object_name = 'nomen_objects'
    form_class = CategoryCreateViewForm
    success_url = reverse_lazy('storageapp:index')

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Добавить категорию'
        return context

storageapp/templates/storageapp/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container d-flex justify-content-between" style="padding: 10px 0;">
    <div>
        <h3>{{title}}</h3>
    </div>
    {% if user.is_superuser %}
    <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{% url 'storageapp:nomen_create' %}" class="btn btn-outline-dark">
            <i class="bi bi-plus-lg"></i> Номен
        </a>
        <a href="{% url 'storageapp:tk_create' %}" class="btn btn-outline-dark">
            <i class="bi bi-plus-lg"></i> ТК
        </a>
        <a href="{% url 'storageapp:category_create' %}" class="btn btn-outline-dark">
            <i class="bi bi-plus-lg"></i> Категорию
        </a>
        <a href="{% url 'storageapp:batch_create' %}" class="btn btn-outline-dark">
            <i class="bi bi-plus-lg"></i> Партию
        </a>
    </div>
    {% endif %}
</div>
<div class="container">
    <div class="col-6">
        <form action="/storage/" method="post" class="col-auto mb-3">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text"
                       class="form-control"
                       placeholder="Введите номер название или артикул товара..."
                       {%if dfs%} value="{{dfs}}" {%endif%}
                       name="data_for_search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" value="OK">Поиск</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="container">
    <a href="{% url 'storageapp:index' %}" class="link-dark">Все({{ products_count|floatformat:0 }})</a>
    {% for item in category_links %}
        <a href="{% url 'storageapp:by_category' item.slug %}" class="link-dark">
            {{item.name}}({{ item.get_products_amount_by_category|floatformat:0 }})
        </a>
    {% endfor %}
</div>

<div class="container">
    {% if objects %}
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Рулоны</th>
            <th scope="col">Нарезка</th>
            <th scope="col">Полки</th>
            <th scope="col">Категория</th>
        </tr>
        </thead>
        <tbody>
        {% for item in objects %}
        <tr>
            <th scope="row">
                <a href="{% url 'storageapp:nomen_detail' item.slug %}" class="link-dark">{{ item.name }}</a>
            </th>
            <td>{{ item.get_quantity|floatformat:0 }}</td>
            <td>{{ item.get_prod_retail }}</td>
            <td>{{ item.get_prod_places }}</td>
            <td>{{ item.category }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {%else%}
    <div>
        <h4>Нет данных. Выберите другой раздел</h4>
    </div>
    {%endif%}
    <div>
    </div>
</div>
{% endblock %}

storageapp/templates/storageapp/nomen_detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}{{ object.name }} :: Редактирование{% endblock %}
{% block content %}

<div class="container">
    <a href="{% url 'storageapp:index' %}" class="link-dark"><i class="bi bi-arrow-left"></i>К товарам</a>
    <h2>{{ title }} {{ object.name }}</h2>
    <p>Артикул: {{ object.part_number }}</p>
    <p>Категория: {{ object.category }}</p>
    <p>Количество: <strong>{{object.get_quantity|floatformat:0 }}</strong></p>
    <p>Доступные партии:</p>
    <div style="max-width: 600px;">
        <table class="table table-sm" style="text-align: center;">
            <tr>
                <th>Партия</th>
                <th>Количество</th>
                <th>Полки</th>
                <th colspan="3">Действия</th>
            </tr>
            {% for item in object.get_prod_batches %}
            <tr>
                <td>{{ item.batch }}</td>
                <td>{{ item.amount|floatformat:0 }}</td>
                <td>{{ item.place }}</td>
                <td><a href="{% url 'storageapp:product_update' item.slug %}" class="link-dark">Изменить</a></td>
                <td><a href="{% url 'storageapp:active' item.slug %}" class="link-dark">Удалить</a></td>
                <td><a href="{% url 'storageapp:roll_to_retail' item.slug %}" class="link-dark">Отдать в нарезку</a></td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="5">
                    <a href="{% url 'storageapp:product_create' object.pk %}">Добавить</a>
                </td>
            </tr>
        </table>
    </div>
    <p>Нарезка</p>
    <div style="max-width: 600px;">
        <table class="table table-sm" style="text-align: center;">
            <tr>
                <th>Партия</th>
                <th>Количество</th>
                <th>Полки</th>
                <th colspan="2">Действия</th>
            </tr>
            {% for item in retail %}
            <tr>
                <td>{{ item.batch }}</td>
                <td>{{ item.amount }}</td>
                <td>{{ item.place }}</td>
                <td><a href="{% url 'storageapp:product_update' item.slug %}" class="link-dark">Изменить</a></td>
                <td><a href="{% url 'storageapp:active' item.slug %}" class="link-dark">Удалить</a></td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="4">
                    <a href="{% url 'storageapp:product_create' object.pk %}">Добавить</a>
                </td>
            </tr>
        </table>
    </div>
    <p>Описание: {{object.description}}</p>
    <p>Намотка: {{ object.meters }} м.п.</p>
    <a href="{% url 'storageapp:nomen_update' object.slug %}" class="link-dark">Редактировать</a>
</div>
{% endblock %}

storageapp/templates/storageapp/product_create_form.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="container" style="max-width: 600px">
    <a href="javascript: history.go(-1)" class="link-dark"><i class="bi bi-arrow-left"></i>Назад</a>
    <div class="card mb-4">
        <div class="card-header">{{ title }}
        </div>
        <div class="card-body">
            <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="container d-flex justify-content-around">
                    <div>
                        <input type="submit" class="form-control btn btn-outline-dark" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

storageapp/templates/storageapp/product_crud_form.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} {{title}} {{obj.name}} {%endblock%}
{% block content %}
<div class="container" style="max-width: 600px">
    <a href="javascript: history.go(-1)" class="link-dark"><i class="bi bi-arrow-left"></i>Назад</a>
    <div class="card mb-4">
        <div class="card-header">{{ title }} <strong>"{{obj.name}}"</strong>
        </div>
        <div class="card-body">
            <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="container d-flex justify-content-around">
                    <div>
                        <input type="submit" class="form-control btn btn-outline-dark" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

storageapp/templates/storageapp/product_detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}{{ object.name }} :: Редактирование{% endblock %}
{% block content %}

<div class="container">
    <a href="{% url 'storageapp:index' %}" class="link-dark"><i class="bi bi-arrow-left"></i>К товарам</a>
    <h2>{{ title }} {{ object.name }}</h2>
    <p>Артикул: {{ object.part_number }}</p>
    <p>Категория: {{ object.category }}</p>
    <p>Количество: <strong>{{object.get_product_sum }}</strong></p>
    <p>Доступные партии:</p>
    <div style="max-width: 40%;">
        <table class="table table-sm" style="text-align: center;">
            <tr>
                <th>Партия</th>
                <th>Количество</th>
                <th colspan="2">Действия</th>
            </tr>
            {% for item in object.get_prod_batches %}
            <tr>
                <td>{{ item.batch }}</td>
                <td>{{ item.amount }}</td>
                <td><a href="{% url 'storageapp:product_update' item.slug %}" class="link-dark">Изменить</a></td>
                <td><a href="{% url 'storageapp:active' item.slug %}" class="link-dark">Удалить</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <p>Описание: {{object.description}}</p>
</div>
{% endblock %}

storageapp/templates/storageapp/shipping_invoice_create.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}
    Отгрузка {{ order.partner.name }}
{% endblock %}
{% block content %}

<div class="container">
    <a href="#{% url 'storageapp:index' %}" class="link-dark"><i class="bi bi-arrow-left"></i>К накладным</a>
    <h5>Номер заказа: {{ order.pk }}</h5>
    <h6>Заказчик: {{ order.partner.name }}</h6>
    <p><b>ТК / Адресс:</b>
        {% if order.tk%}{{ order.tk.name }}
        {% elif order.self_pickup%}Самовывоз
        {% elif order.partner.address%}{{ order.partner.address }}
        {%endif%}
    </p>

    <table class="table">
        <tr>
            <th>Товар</th>
            <th>Количество</th>
            <th>Партия</th>
        </tr>
        {% for item in objects %}
            <tr>
                <td>{{item.product.name}}</td>
                <td>{{item.amount}}</td>
                <td>
                    <select aria-label="Партия">
                        {% for product in item.get_batches_by_product %}
                        <option>{{ product }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Сохранить">
    <input type="submit" value="Отгрузить">
</div>
{% endblock %}