mainapp/urls.py
from django.urls import path

from .views import index, back_up

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('backup/', back_up, name='backup'),
]

ordersapp/urls.py
from django.urls import path

from .views import OrderActiveListView, OrderDetailView, get_order_list, order_delete, set_payed, OrderCreateView, \
    OrderUpdateView, OrderProductCreate, order_product_delete, \
    set_shipped, set_for_delivery, order_product_update, statistics

app_name = 'ordersapp'

urlpatterns = [
    path('', get_order_list, name='index'),
    path('active/', OrderActiveListView.as_view(), name='active_orders'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('update/<int:pk>', OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>', order_delete, name='order_delete'),
    path('payed/<int:pk>', set_payed, name='order_payed'),
    path('shipped/<int:pk>', set_shipped, name='order_shipped'),
    path('for_delivery/<int:pk>', set_for_delivery, name='for_delivery'),

    path('product_create/<int:pk>', OrderProductCreate.as_view(), name='order_product_create'),
    path('product_delete/<int:pk>', order_product_delete, name='order_product_delete'),
    path('product_update/<int:order_pk>/<int:good_pk>', order_product_update, name='order_product_update'),

    path('statistic/', statistics, name='statistics'),
]

storageCRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('todo/', include('todoapp.urls', namespace='todoapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('partners/', include('partnersapp.urls', namespace='partnersapp')),
    path('storage/', include('storageapp.urls', namespace='storageapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('transport/', include('transportapp.urls', namespace='transportapp')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .additional_functions import do_backup
from ordersapp.models import OrderList
from todoapp.models import ToDoList


@login_required
def index(request):
    todo_block = ToDoList.objects.filter(is_active=True).order_by('-id')[0:4]
    order_list = OrderList.objects.filter(shipped=False)
    context = {
        'todo_objects': todo_block,
        'title': 'Система управления складом',
        'order_objects': order_list,
    }
    return render(request, 'mainapp/index.html', context)


@login_required
def back_up(request):

    do_backup()

    return HttpResponseRedirect(reverse('mainapp:index'))

mainapp/templates/includes/inc_active_orders.html
{% load static %}
<h4>Активные заказы</h4>
    <a href="{% url 'ordersapp:index' %}" class="link-dark" style="margin-left: 16px;">
        <i class="bi bi-arrow-left"></i> Перейти к заказам</a>
<table class="table">
    <thead>
    <tr>
        <th>Номер</th>
        <th>Покупатель</th>
        <th>Товар/Количество</th>
        <th>ТК/Адрес</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
        {% for item in order_objects %}
        <tr>
            <td>
                <a href="{% url 'ordersapp:order_detail' item.pk%}" class="link-dark">
                    <b>Заказ № {{ item.pk }}</b>
                </a>
                <br>{{ item.created_at|date:"d.m.Y" }}
            </td>
            <td>
                <a href="{% url 'ordersapp:order_detail' item.pk%}" class="link-dark">
                    {{ item.partner.partner_city }}, {{ item.partner.name }}
                </a>
            </td>
            <td>
                <table>
                    {% for good in item.get_order_products_list %}
                    <tr>
                        <td>{{ good.product.name }}:</td>
                        <td style="text-align:center;width: 30%">{{ good.amount|floatformat:0  }} шт.</td>
                    </tr>
                    {% endfor %}
                </table>
            </td>
            <td>
                {%if item.tk%}
                    <img src="{{item.tk.logo}}" style="height: 20px;"> {{ item.tk }}
                {%endif%}
                {%if item.self_pickup%}
                Самовывоз
                {%elif item.partner.address%}<i class="bi bi-truck"></i>
                        {{item.partner.address}} <br>
                    <a href="https://yandex.ru/maps/?text={{item.partner.address}}" class="link-dark" target="_blank">
                        Посмотреть на карте <i class="bi bi-box-arrow-up-right"></i>
                    </a>
                {%endif%}

            </td>
            <td>
                {% if not item.payed and not item.shipped %}
                    <span class="badge bg-info text-dark">Новый</span>
                {%endif%}
                {% if item.payed %}
                    <span class="badge bg-warning text-dark">Оплачен</span><br>
                {% endif %}
                {% if item.shipped %}
                    <span class="badge bg-success">Отгружен</span>
                {% endif %}
            </td>
        </tr>
        <tr style="border-bottom:1px solid black">
            <td colspan="5"><span style="margin-left: 16px;">Комментарий: {{ item.comment}}</span></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

mainapp/templates/includes/inc_footer.html
{% load static %}
<div class="bg-dark min-vw-100 d-flex justify-content-around text-white align-items-center">
    <div id="weather">
        <p>В Москве:<img src="{{ icon }}" alt="" style="width: 20%">{{ temp }}&deg;С</p>
    </div>
    <div id="currency">
        <p>Доллар: {{d_value_now}} / {{d_value_prev}}</p>
    </div>
</div>

mainapp/templates/includes/inc_head_menu.html
{% load static %}

<div class="bg-dark min-vw-100 d-flex justify-content-between text-white">
    <div>
            <a href="/" class="align-items-center text-white text-decoration-none">
                <i class="bi bi-arrows-fullscreen"></i> <span class="fs-5 d-none d-sm-inline"> KSK_CRM</span>
            </a>
        </div>
    <div class="d-flex justify-content-center">
        <ul class="nav nav-pills mb-6 " id="menu">
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'mainapp:index' %}" class="nav-link align-middle px-0 link-light">
                    <i class="bi bi-house"></i> <span class="ms-1 d-none d-sm-inline color-white">Главная</span>
                </a>
            </li>
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'todoapp:index' %}" class="nav-link align-middle px-0 link-light">
                    <i class="bi bi-list-task"></i> <span class="ms-1 d-none d-sm-inline color-white">Задачи</span>
                </a>
            </li>
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'ordersapp:index' %}" class="nav-link align-middle px-0 link-light">
                    <i class="bi bi-aspect-ratio"></i> <span class="ms-1 d-none d-sm-inline color-white">Заказы</span>
                </a>
            </li>
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'storageapp:index' %}" class="nav-link px-0 align-middle link-light">
                    <i class="bi bi-box-seam"></i> <span class="ms-1 d-none d-sm-inline color-white">Склад</span>
                </a>
            </li>
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'partnersapp:index' %}" class="nav-link align-middle px-0 link-light">
                    <i class="bi bi-person-square"></i> <span class="ms-1 d-none d-sm-inline color-white">Контрагенты</span>
                </a>
            </li>
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'transportapp:index' %}" class="nav-link align-middle px-0 link-light">
                    <i class="bi bi-truck"></i> <span class="ms-1 d-none d-sm-inline color-white">Транспорт</span>
                </a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item mx-auto ps-3">
                <a href="{% url 'admin:index' %}" class="nav-link align-middle px-0 link-light" target="_blank">
                    <i class="bi bi-diagram-3"></i> <span class="ms-1 d-none d-sm-inline color-white">Админка</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div id="user_place">
        {% if user.first_name %}
            {{user.first_name}}
        {% else %}
            {{user.username}}
        {% endif %}|
        <a href="{% url 'logout' %}" class="link-light">Выход</a>
    </div>
</div>

mainapp/templates/includes/inc_header.html
{% load static %}

<nav class="navbar">
    <div class="container d-flex justify-content-between">
        <div id="weather">
            <p>В Москве:<img src="{{ icon }}" alt="">{{ temp }}&deg;С, {{ conditions }}</p>
        </div>
    </div>
</nav>

mainapp/templates/includes/inc_left_side_menu.html
{% load static %}
<div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100 p-3">
    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <i class="bi bi-arrows-fullscreen"></i> <span class="fs-5 d-none d-sm-inline"> KSK_CRM</span>
    </a>
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
        <li class="nav-item">
            <a href="{% url 'mainapp:index' %}" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-house"></i> <span class="ms-1 d-none d-sm-inline color-white">Главная</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'todoapp:index' %}" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-list-task"></i> <span class="ms-1 d-none d-sm-inline color-white">Задачи</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'ordersapp:index' %}" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-aspect-ratio"></i> <span class="ms-1 d-none d-sm-inline color-white">Заказы</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'storageapp:index' %}" class="nav-link px-0 align-middle link-light">
                <i class="bi bi-box-seam"></i> <span class="ms-1 d-none d-sm-inline color-white">Склад</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'partnersapp:index' %}" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-person-square"></i> <span class="ms-1 d-none d-sm-inline color-white">Контрагенты</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-bar-chart-line"></i> <span class="ms-1 d-none d-sm-inline color-white">Статистика</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-truck"></i> <span class="ms-1 d-none d-sm-inline color-white">Транспорт</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link align-middle px-0 link-light">
                <i class="bi bi-diagram-3"></i> <span class="ms-1 d-none d-sm-inline color-white">Админка</span>
            </a>
        </li>
    </ul>
    <div id="weather">
        <p>В Москве:<img src="{{ icon }}" alt="">{{ temp }}&deg;С</p>
        <p>{{ conditions }}</p>
        <hr>
    </div>
    <div id="exchange">
        <h5 style="font-color: white;">Курсы ЦБ</h5>
        <table class="table table-dark">
            <thead>
                <th>Валюта</th>
                <th>Текущий</th>
                <th>Прошлый</th>
            </thead>
            <tbody>
            <tr>
                <td>Доллар</td>
                <td>{{d_value_now}}</td>
                <td>{{d_value_prev}}</td>
            </tr>
            <tr>
                <td>Юань</td>
                <td>{{yu_value_now}}</td>
                <td>{{yu_value_prev}}</td>
            </tr>
            <tr>
                <td>Воны</td>
                <td>{{kr_value_now}}</td>
                <td>{{kr_value_prev}}</td>
            </tr>
            </tbody>
        </table>
    </div>

</div>