mainapp/urls.py
from django.urls import path

from .views import index, back_up

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('backup/', back_up, name='backup'),
]

ordersapp/urls.py
from django.urls import path

from .views import OrderActiveListView, OrderDetailView, get_order_list, order_delete, set_payed, OrderCreateView, \
    OrderUpdateView, OrderProductCreate, order_product_delete, \
    set_shipped, set_for_delivery, order_product_update, statistics

app_name = 'ordersapp'

urlpatterns = [
    path('', get_order_list, name='index'),
    path('active/', OrderActiveListView.as_view(), name='active_orders'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('update/<int:pk>', OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>', order_delete, name='order_delete'),
    path('payed/<int:pk>', set_payed, name='order_payed'),
    path('shipped/<int:pk>', set_shipped, name='order_shipped'),
    path('for_delivery/<int:pk>', set_for_delivery, name='for_delivery'),

    path('product_create/<int:pk>', OrderProductCreate.as_view(), name='order_product_create'),
    path('product_delete/<int:pk>', order_product_delete, name='order_product_delete'),
    path('product_update/<int:order_pk>/<int:good_pk>', order_product_update, name='order_product_update'),

    path('statistic/', statistics, name='statistics'),
]

storageCRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('todo/', include('todoapp.urls', namespace='todoapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('partners/', include('partnersapp.urls', namespace='partnersapp')),
    path('storage/', include('storageapp.urls', namespace='storageapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('transport/', include('transportapp.urls', namespace='transportapp')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ordersapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from partnersapp.models import PartnersList
from storageapp.models import NomenList, BatchList, ProductList


class TKList(models.Model):
    name = models.CharField(verbose_name='Название', max_length=50)
    logo = models.URLField(verbose_name='ссылка на картинку', blank=True)

    class Meta:
        db_table = 'TK_list'
        verbose_name = ("Транспортная")
        verbose_name_plural = ("Транспортные")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("TK_detail", kwargs={"pk": self.pk})


class OrderList(models.Model):

    created_at = models.DateField(
        verbose_name='Дата создания',
        auto_now_add=True)
    partner = models.ForeignKey(
        PartnersList,
        on_delete=models.PROTECT,
        verbose_name='Контрагент',
        related_name='orderlist')
    self_pickup = models.BooleanField(verbose_name='Самовывоз', default=False)
    tk = models.ForeignKey(
        TKList,
        verbose_name='Транспортная',
        on_delete=models.SET_NULL,
        null=True,
        blank=True)
    payed = models.BooleanField(verbose_name='Оплачен', default=False)
    shipped = models.BooleanField(verbose_name='Отгружено', default=False)
    shipped_date = models.DateField(
        verbose_name='Дата отгрузки', blank=True, null=True)
    for_delivery = models.BooleanField(verbose_name='На доставку', default=False)
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    user_creator = models.ForeignKey(
        User,
        verbose_name='Создатель',
        on_delete=models.SET_NULL,
        null=True)

    class Meta:
        db_table = 'order_list'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['shipped', '-shipped_date', '-created_at', '-pk']

    def __str__(self):
        return f'№{self.pk} от {self.created_at}, {self.partner.name}'

    def get_absolute_url(self):
        return reverse('ordersapp:order_detail', kwargs={'pk': self.pk})

    def get_order_products_list(self):
        return OrderProductsList.objects.filter(order=self.pk)


class OrderProductsList(models.Model):
    product = models.ForeignKey(
        NomenList,
        on_delete=models.PROTECT,
        verbose_name='Товар',
        related_name='orderproduct')
    order = models.ForeignKey(
        OrderList,
        on_delete=models.CASCADE,
        verbose_name='Заказ',
        related_name='orderproduct_o')
    batch = models.ForeignKey(BatchList, on_delete=models.CASCADE, verbose_name='Партия', related_name='batches_o', blank=True, null=True)
    is_retail = models.BooleanField(verbose_name='Нарезка', default=False)
    amount = models.FloatField(verbose_name='Количество')

    class Meta:
        db_table = 'orderproductlist'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.product.name

    def get_absolute_url(self):
        return reverse('ordersapp:order_detail', kwargs={'pk': self.pk})

    def get_prod_by_product(self):
        products = ProductList.objects.filter(name__name=self.product)
        return products

    def get_batches_by_product(self):
        return ProductList.objects.filter(name__name=self.product.name, is_active=True)

ordersapp/forms.py
from django import forms

from .models import OrderList, OrderProductsList


class SearchForm(forms.Form):
    pass


class NewOrderForm(forms.ModelForm):
    class Meta:
        model = OrderList
        exclude = ('created_at', 'user_creator', 'shipped', 'shipped_date', 'for_delivery')
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 2, 'cols': 30}),
        }


class UpdateOrderForm(forms.ModelForm):
    class Meta:
        model = OrderList
        exclude = ('created_at', 'shipped_date', 'shipped', 'for_delivery', 'user_creator')
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 2, 'cols': 30}),
        }


class OrderProductForm(forms.ModelForm):
    class Meta:
        model = OrderProductsList
        exclude = ('order',)


class OrderProductUpdateForm(forms.ModelForm):

    class Meta:
        model = OrderProductsList
        exclude = ('order',)

ordersapp/views.py
from datetime import datetime, date

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from partnersapp.models import PartnersList
from storageapp.models import BatchList, ProductList, NomenList
from transportapp.models import RideList
from .adiitional_functions import count_sold_products
from .forms import SearchForm, NewOrderForm, UpdateOrderForm, OrderProductForm
from .models import OrderList, OrderProductsList


@login_required
def get_order_list(request):
    objects = OrderList.objects.all()
    paginator = Paginator(objects, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.method == 'POST':
        form = SearchForm(request.POST)

        if form.is_valid():
            search_results = []
            data_for_search = form.data['data_for_search']

            if data_for_search.isdigit():
                search_results = list(
                    OrderList.objects.filter(
                        pk=int(data_for_search)))
            search_results = set(
                list(
                    OrderList.objects.filter(
                        partner__partner_city__contains=data_for_search)) +
                list(
                    OrderList.objects.filter(
                        partner__name__contains=data_for_search)) +
                list(
                    OrderList.objects.filter(
                        partner__address__contains=data_for_search)) +
                list(
                    OrderList.objects.filter(
                        tk__name__contains=data_for_search)) +
                search_results)
            context = {
                'page_obj': search_results,
                'form': form,
                'dfs': data_for_search,
            }
            return render(request, 'ordersapp/index.html', context)

    context = {
        'page_obj': page_obj,
        'title': 'Все заказы',
    }
    return render(request, 'ordersapp/index.html', context)


class OrderActiveListView(LoginRequiredMixin, ListView):
    """ Общий вывод активных заказов """
    model = OrderList
    template_name = 'ordersapp/index.html'
    context_object_name = 'objects'
    paginate_by = 10

    def get_queryset(self):
        return OrderList.objects.filter(shipped=False)

    def get_context_data(self, **kwargs):
        context = super(OrderActiveListView, self).get_context_data(**kwargs)
        context['title'] = 'Заказы в работе'
        return context


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = OrderList
    template_name = 'ordersapp/order_detail.html'
    context_object_name = 'object'

    def get_context_data(self, *args, **kwargs):
        context = super(OrderDetailView, self).get_context_data(*args, **kwargs)
        try:
            ride = get_object_or_404(RideList, order=self.object)
            context['ride'] = ride
        except:
            pass
        return context


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = OrderList
    template_name = 'ordersapp/order_crud_form.html'
    form_class = NewOrderForm

    def form_valid(self, form):
        form.instance.user_creator = self.request.user
        return super(OrderCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новый заказ'
        return context


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = OrderList
    template_name = 'ordersapp/order_crud_form.html'
    form_class = UpdateOrderForm

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse('ordersapp:order_detail', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование заказа'
        context['obj'] = OrderList.objects.get(pk=self.kwargs['pk'])
        return context


@login_required
def order_delete(request, pk):
    order = get_object_or_404(OrderList, pk=pk)
    if request.method == 'GET':
        order.delete()
    return HttpResponseRedirect(reverse('ordersapp:index'))


@login_required
def set_payed(request, pk):
    order = get_object_or_404(OrderList, pk=pk)
    if request.method == 'GET':
        if order.payed:
            order.payed = False
        else:
            order.payed = True
        order.save()

        return HttpResponseRedirect(
            reverse(
                'ordersapp:order_detail',
                kwargs={
                    'pk': pk}))


@login_required
def set_shipped(request, pk):
    order = get_object_or_404(OrderList, pk=pk)
    if request.method == 'GET':

        if order.shipped:
            order.shipped = False
            order_products = OrderProductsList.objects.filter(order=pk)
            for o_prod in order_products:
                product = get_object_or_404(ProductList, name=o_prod.product, batch=o_prod.batch, is_retail=o_prod.is_retail)
                product.amount = product.amount + o_prod.amount
                product.save()
        else:
            order.shipped = True
            order.shipped_date = datetime.now()
            order_products = OrderProductsList.objects.filter(order=pk)
            for o_prod in order_products:
                product = get_object_or_404(ProductList, name=o_prod.product, batch=o_prod.batch, is_retail=o_prod.is_retail)
                product.amount = product.amount - o_prod.amount
                product.save()

        order.save()

        return HttpResponseRedirect(
            reverse(
                'ordersapp:order_detail',
                kwargs={
                    'pk': pk}))


@login_required
def set_for_delivery(request, pk):
    order = get_object_or_404(OrderList, pk=pk)
    if request.method == 'GET':
        if order.for_delivery:
            order.for_delivery = False
            ride = get_object_or_404(RideList, order=order)
            ride.delete()
        else:
            order.for_delivery = True

            if order.tk:
                ride_adr = order.tk
            else:
                ride_adr = order.partner.address
            ride = RideList(
                title='Доставка пленки',
                address=ride_adr,
                order=order,
            )
            ride.save()
        order.save()

        return HttpResponseRedirect(
            reverse(
                'ordersapp:order_detail',
                kwargs={
                    'pk': pk}))


class OrderProductCreate(LoginRequiredMixin, CreateView):
    model = OrderProductsList
    form_class = OrderProductForm
    template_name = 'ordersapp/order_product_create.html'

    def form_valid(self, form):
        order = OrderList.objects.get(pk=self.kwargs['pk'])
        self.object = form.save(commit=False)
        self.object.order = order
        self.object.save()

        return HttpResponseRedirect(
            reverse(
                'ordersapp:order_detail',
                kwargs={
                    'pk': order.pk}))


@login_required
def order_product_delete(request, pk):
    product = get_object_or_404(OrderProductsList, pk=pk)
    if request.method == 'GET':
        product.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def order_product_update(request, order_pk, good_pk):
    object = get_object_or_404(OrderProductsList, pk=good_pk)

    if request.method == 'POST':

        retail = request.POST.getlist('is_retail')
        if len(retail) > 0:
            object.is_retail = True
        else:
            object.is_retail = False

        b_slug = request.POST.get('batch').split('-')[1]
        batch = get_object_or_404(BatchList, slug=b_slug)
        amount = float(request.POST.get('amount').replace(',', '.'))

        object.batch = batch
        object.amount = amount

        object.save()

        return HttpResponseRedirect(reverse('ordersapp:order_detail', kwargs={'pk': order_pk}))

    context = {
        'title': 'Редактирование товара',
        'object': object,
    }
    return render(request, 'ordersapp/order_product_crud.html', context)


@login_required
def statistics(request):
    clients = PartnersList.objects.all()
    selected_client = request.POST.get('client_list')
    date_from = request.POST.get('date_from')
    date_to = request.POST.get('date_to')
    objects = None
    calc_objects = None

    if selected_client:
        partner = PartnersList.objects.get(name=selected_client.split('|')[1].strip())
    else:
        partner = ''

    if date_to == '':
        date_to = date.today().strftime("%Y-%m-%d")
    if date_from == '':
        date_from = date(2020, 1, 1).strftime("%Y-%m-%d")

    if request.method == 'POST':
        if partner == '':
            calc_objects = OrderProductsList.objects.filter(order__shipped_date__gte=date_from,
                                                            order__shipped_date__lte=date_to,
                                                            is_retail=False)
            if len(calc_objects) > 0:
                objects = count_sold_products(calc_objects)
        else:
            calc_objects = OrderProductsList.objects.filter(order__partner=partner,
                                                            order__shipped_date__gte=date_from,
                                                            order__shipped_date__lte=date_to,
                                                            is_retail=False)
            if len(calc_objects) > 0:

ordersapp/templates/ordersapp/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<br>
<div class="container">
    <div>
        <h3>{{title}}</h3>
    </div>
</div>
<div class="d-flex justify-content-between">
    <div>
        <a href="{% url 'ordersapp:index' %}" class="btn btn-outline-dark mb-3">Все</a>
        <a href="{% url 'ordersapp:active_orders' %}" class="btn btn-outline-success mb-3">Активные</a>
        <a href="{% url 'ordersapp:statistics' %}" class="btn btn-outline-primary mb-3">Статистики</a>
    </div>
    <div class="col-6">
        <form action="/orders/" method="post" class="col-auto mb-3">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" class="form-control"
                       {%if dfs%} value="{{dfs}}" {%endif%}
                       placeholder="Введите номер заказа, контрагента, адрес" name="data_for_search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" value="OK">Поиск</button>
                </div>
            </div>
        </form>
    </div>
    <div>
        <a href="{% url 'ordersapp:order_create' %}" class="btn btn-outline-dark mb-3">
            <i class="bi bi-plus-lg"></i> Новый Заказ
        </a>
    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th>Номер</th>
        <th>Покупатель</th>
        <th>Товар: Количество</th>
        <th>ТК/Адрес</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
        {% for item in page_obj %}
        <tr>
            <td>
                <a href="{% url 'ordersapp:order_detail' item.pk%}" class="link-dark">
                    <b>Заказ № {{ item.pk }}</b>
                </a>
                <br>{{ item.created_at|date:"d.m.Y" }}
            </td>
            <td>
                <a href="{% url 'ordersapp:order_detail' item.pk%}" class="link-dark">
                    {{ item.partner.partner_city }}, {{ item.partner.name }}
                </a><br>
                {% if item.shipped %}
                    <span style="font-size: 12px;">Отгружен {{ item.shipped_date|date:"d.m.Y" }}</span>
                {% endif %}
            </td>
            <td>
                <table>
                    {% for good in item.get_order_products_list %}
                    <tr>
                        <td>{{ good.product.name }}:</td>
                        <td style="text-align:center;width: 30%">
                            {% if good.is_retail %}
                                {{ good.amount }} м.п.
                            {% else %}
                                {{ good.amount|floatformat:0 }} шт.
                            {% endif %}
                        </td>

                    </tr>
                    {% endfor %}
                </table>
            </td>
            <td>
                {%if item.tk%}
                    <img src="{{item.tk.logo}}" style="height: 20px;"> {{ item.tk }}
                {%endif%}
                {%if item.self_pickup%}
                Самовывоз
                {%elif item.partner.address%}<i class="bi bi-truck"></i>
                        {{item.partner.address}} <br>
                    <a href="https://yandex.ru/maps/?text={{item.partner.address}}" class="link-dark" target="_blank">
                        Посмотреть на карте <i class="bi bi-box-arrow-up-right"></i>
                    </a>
                {%endif%}

            </td>
            <td>
                {% if not item.payed and not item.shipped %}
                    <span class="badge bg-info text-dark">Новый</span>
                {%endif%}
                {% if item.payed %}
                    <span class="badge bg-warning text-dark">Оплачен</span><br>
                {% endif %}
                {% if item.shipped %}
                    <span class="badge bg-success">Отгружен</span>
                {% endif %}
            </td>
        </tr>
        <tr style="border-bottom:1px solid black">
            <td colspan="5"><span style="margin-left: 16px;">Комментарий: {{ item.comment}}</span></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page=1" class="page-link link-dark">Первая</a>
            </li>
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link link-dark">&laquo;</a>
            </li>
        {% endif %}

        {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
                <a href="?page={{page}}" class="page-link link-dark">{{page}}</a>
            </li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link link-dark">&raquo;</a>
            </li>
            <li>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link link-dark">Последняя</a>
            </li>
        {% endif %}
    </ul>
</nav>

<br><br><br>
<div class="container">
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_crud_form.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="container" style="max-width: 600px">
    <a href="javascript: history.go(-1)" class="link-dark"><i class="bi bi-arrow-left"></i>Назад</a>
    <div class="card mb-4">
        <div class="card-header">{{ title }} № {{ obj.pk }}</div>
        <div class="card-body">
            <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Контрагент: {{ form.partner }}</p>
                <hr>
                <h6>Способ получения</h6>
                <span style="font-size: 11px;">*В случае доставки до адреса контрагента - оставить поля пустыми*</span>
                <p>
                    {{ form.self_pickup.errors}}
                    <label for="{{ form.self_pickup.id_for_label }}">Самовывоз:</label>
                    {{form.self_pickup}} или Транспортная: {{form.tk}}
                </p>
                <hr>
                <h6>Необязательные аргументы</h6>
                <p>
                    <label for="{{ form.payed.id_for_label }}">Оплачен:</label>
                     {{form.payed}}
                </p>
                Комментарий: <br>{{form.comment}}
                <hr>
                <div class="container d-flex justify-content-around">
                    <div>
                        <input type="submit" class="form-control btn btn-outline-dark" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} {{object.pk}} | {{object.created_at|date:"d.m.Y"}} | {{object.partner.name}} {% endblock %}

{% block content %}

<div class="container">
    <p>
        <a href="{% url 'ordersapp:index' %}" class="link-dark"><i class="bi bi-arrow-left"></i>К заказам</a>
    </p>
    <h2>{{object.partner.partner_city}}, {{object.partner.name}}</h2>
    <p><b>Заказ № {{ object.pk }}</b></p>
    <p><b>Создан:</b> {{object.created_at}}, {{object.user_creator.first_name}}</p>
    <p><b>ТК / Адресс:</b>
        {% if object.tk%}{{ object.tk.name }}
        {% elif object.self_pickup%}Самовывоз
        {% elif object.partner.address%}{{ object.partner.address }}
        {%endif%}
    </p>
    <table class="table caption-top">
        <caption>Список товаров:</caption>
        <thead>
            <tr>
                <th>Название</th>
                <th></th>
                <th>Количество</th>
                <th>
                    {% if not object.shipped %}
                        <a href="{% url 'ordersapp:order_product_create' object.pk %}" class="link-primary">Добавить</a>
                    {% endif %}
                </th>
            </tr>
        </thead>
        <tbody>
        {%for item in object.get_order_products_list%}
            <tr>
                <td>
                    {% if not object.shipped %}
                    <a href="{% url 'ordersapp:order_product_update' object.pk item.pk %}">
                        {{ item.product.name }}
                    </a>
                    {% else %}
                    <p>
                        {{ item.product.name }}
                    </p>
                    {% endif %}
                </td>
                <td>
                    {% if item.batch %} {{item.batch}} {%endif%}
                </td>
                <td>
                    {% if item.is_retail %}
                        {{ item.amount }} м.п.
                    {% else %}
                        {{ item.amount|floatformat:0 }} шт.
                    {% endif %}
                </td>
                <td>
                    {% if not object.shipped %}
                        <a href="{% url 'ordersapp:order_product_delete' item.pk %}" class="link-primary">Удалить</a>
                    {% endif %}
                </td>
            </tr>
        {%endfor%}
        </tbody>
    </table>
    <p><b>Комментарий:</b> {{ object.comment }}</p>
</div>

<div class="container d-flex justify-content-between">
    {%if object.payed%}
        <p>Оплачен |
        <a href="{% url 'ordersapp:order_payed' object.pk %}" style="font-size: 12px; text-decoration: none; border-bottom: 1px dashed;">Отменить
        </a></p>
    {% else %}
        <a href="{% url 'ordersapp:order_payed' object.pk %}" class="btn btn-outline-warning mb-3">Оплатили</a>
    {%endif%}
    {%if object.shipped%}
        {% if ride.delivered %}
            <p>Отгружено: {{ object.shipped_date|date:"d.m.Y" }}</p>
        {% else %}
            <p>Отгружено: {{ object.shipped_date|date:"d.m.Y" }} |
            <a href="{% url 'ordersapp:order_shipped' object.pk %}" style="font-size: 12px; text-decoration: none; border-bottom: 1px dashed;">Отменить
            </a></p>
        {% endif %}
    {% else %}
        <a href="{% url 'ordersapp:order_shipped' object.pk %}" class="btn btn-outline-success mb-3">Отгрузить</a>
    {%endif%}
    {% if not object.self_pickup %}
        {% if object.for_delivery %}
            {% if ride.delivered %}
                <p>
                    Доставлено: {{ ride.delivered_at|date:"d.m.Y" }}
                </p>
            {% else %}
                <p>В доставке |
                    <a href="{% url 'ordersapp:for_delivery' object.pk %}" style="font-size: 12px; text-decoration: none; border-bottom: 1px dashed;">Отменить</a>
                </p>
            {% endif %}
        {% else %}
            <a href="{% url 'ordersapp:for_delivery' object.pk %}" class="btn btn-outline-info mb-3">
                На доставку
            </a>
        {% endif %}
    {% endif %}
</div>
<div class="container">
    <a href="{% url 'ordersapp:order_update' object.pk %}" class="btn btn-outline-primary mb-3 {% if object.shipped %} disabled {%endif%}">Редактировать</a>
    <a href="{% url 'ordersapp:order_delete' object.pk %}" class="btn btn-outline-danger mb-3 {% if object.shipped %} disabled {%endif%}">Удалить</a>
</div>

{% endblock %}

ordersapp/templates/ordersapp/order_product_create.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="container" style="max-width: 600px">
    <a href="javascript: history.go(-1)" class="link-dark"><i class="bi bi-arrow-left"></i>Назад</a>
    <div class="card mb-4">
        <div class="card-header">Добавить товар</div>
        <div class="card-body">
            <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    Товар: {{ form.product }}
                </p>
                <p>Количество: {{ form.amount }} </p>
                <p>
                    Нарезка {{ form.is_retail }} <span style="font-size: 11px;">*Поставить, если отрезаем от рулона*</span>
                </p>
                <hr>
                <h6>Необязательные аргументы</h6>
                <p>
                    Партия: {{ form.batch }}
                </p>
                <hr>
                <div class="container d-flex justify-content-around">
                    <div>
                        <input type="submit" class="form-control btn btn-outline-dark" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_product_crud.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} {{ title }} {{ obj.name }}{% endblock %}
{% block content %}
<div class="container" style="max-width: 600px">
    <a href="javascript: history.go(-1)" class="link-dark"><i class="bi bi-arrow-left"></i>Назад</a>
    <div class="card mb-4">
        <div class="card-header">{{ title }}
        </div>
        <div class="card-body">
            <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Наименование: {{ object.product }}</p>
                <p>Количество:
                    <input type="text" value="{{ object.amount }}" name="amount">
                </p>
                <p>
                    <select aria-label="Партия" id="batch" name="batch" value="{{object.batch}}">
                        {% for obj in object.get_batches_by_product %}
                        <option value="{{obj}}" {%if object.batch == obj.batch %}selected {%endif%}>{{obj}}</option>
                        {% endfor %}
                    </select>
                </p>
                <p><label for="is_retail">Нарезка</label>
                    <input type="checkbox" name="is_retail" id="is_retail" {% if object.is_retail %} checked {% endif %}>
                </p>

                <div class="container d-flex justify-content-around">
                    <div>
                        <input type="submit" class="form-control btn btn-outline-dark" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}