mainapp/urls.py
from django.urls import path

from .views import index, back_up

app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('backup/', back_up, name='backup'),
]

ordersapp/urls.py
from django.urls import path

from .views import OrderActiveListView, OrderDetailView, get_order_list, order_delete, set_payed, OrderCreateView, \
    OrderUpdateView, OrderProductCreate, order_product_delete, \
    set_shipped, set_for_delivery, order_product_update, statistics

app_name = 'ordersapp'

urlpatterns = [
    path('', get_order_list, name='index'),
    path('active/', OrderActiveListView.as_view(), name='active_orders'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('update/<int:pk>', OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>', order_delete, name='order_delete'),
    path('payed/<int:pk>', set_payed, name='order_payed'),
    path('shipped/<int:pk>', set_shipped, name='order_shipped'),
    path('for_delivery/<int:pk>', set_for_delivery, name='for_delivery'),

    path('product_create/<int:pk>', OrderProductCreate.as_view(), name='order_product_create'),
    path('product_delete/<int:pk>', order_product_delete, name='order_product_delete'),
    path('product_update/<int:order_pk>/<int:good_pk>', order_product_update, name='order_product_update'),

    path('statistic/', statistics, name='statistics'),
]

storageCRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('todo/', include('todoapp.urls', namespace='todoapp')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('partners/', include('partnersapp.urls', namespace='partnersapp')),
    path('storage/', include('storageapp.urls', namespace='storageapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('transport/', include('transportapp.urls', namespace='transportapp')),
    path('accounts/', include('django.contrib.auth.urls')),
]

transportapp/urls.py
from django.urls import path

from .views import get_ride_list, RideActiveListView, RideCreateView, set_delivered, ride_delete, MileageListView, \
    MileageCreateView, delete_mileage

app_name = 'transportapp'

urlpatterns = [
    path('', get_ride_list, name='index'),
    path('active/', RideActiveListView.as_view(), name='active_rides'),
    path('create/', RideCreateView.as_view(), name='ride_create'),
    path('set_delivered/<int:pk>', set_delivered, name='ride_delivered'),
    path('delete/<int:pk>', ride_delete, name='ride_delete'),

    path('mileage/', MileageListView.as_view(), name='mileage_list'),
    path('mileage/create/', MileageCreateView.as_view(), name='mileage_create'),
    path('mileage/delete/<int:pk>', delete_mileage, name='mileage_delete'),
]

transportapp/models.py
from django.db import models
from django.urls import reverse

from ordersapp.models import OrderList


class RideList(models.Model):
    title = models.CharField(verbose_name='Цель', max_length=256)
    address = models.CharField(verbose_name='Адрес', max_length=256, blank=True)
    order = models.OneToOneField(OrderList, verbose_name='Заказ', on_delete=models.PROTECT, blank=True, null=True, related_name='ridelist')
    description = models.TextField(verbose_name='Описание', blank=True)
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True)
    delivered = models.BooleanField(verbose_name='Доставлено', default=False)
    delivered_at = models.DateTimeField(verbose_name='Дата доставки', blank=True, null=True)

    class Meta:
        db_table = 'ridelist'
        verbose_name = 'Поездка'
        verbose_name_plural = 'Поездки'
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('transportapp:index')


class CarList(models.Model):
    name = models.CharField(verbose_name='Название', max_length=128)
    km_real = models.PositiveIntegerField(verbose_name='Пробег (ОДО)')
    km_docs = models.PositiveIntegerField(verbose_name='Пробег (ДОК)')
    consumption = models.PositiveIntegerField(verbose_name='Расход на 100 км')
    gos_num = models.CharField(verbose_name='Гос Номер', max_length=10, blank=True)
    sts = models.CharField(verbose_name='Гос Номер', max_length=20, blank=True)

    class Meta:
        db_table = 'carlist'
        verbose_name = 'Машина'
        verbose_name_plural = 'Машины'

    def __str__(self):
        return f'{self.name}, {self.gos_num}'

    def get_absolute_url(self):
        return reverse('transportapp:index')


class MileageList(models.Model):
    created_at = models.DateTimeField(verbose_name='Дата')
    car = models.ForeignKey(CarList, verbose_name='Машина', on_delete=models.PROTECT)
    km_start = models.PositiveIntegerField(verbose_name='Пробег (Начало)')
    km_end = models.PositiveIntegerField(verbose_name='Пробег (Конец)')
    km_amount = models.PositiveIntegerField(verbose_name='Пробег (За день)', default=0)
    km_docs = models.PositiveIntegerField(verbose_name='Пробег (Док)')
    consumption = models.PositiveIntegerField(verbose_name='Расход за день')
    comment = models.CharField(verbose_name='Комментарий', max_length=512, blank=True)

    class Meta:
        db_table = 'mileagelist'
        verbose_name = 'Пробег'
        verbose_name_plural = 'Пробеги'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.car.name}, {self.created_at}'

    def get_absolute_url(self):
        return reverse('transportapp:index')

transportapp/forms.py
from django import forms

from .models import RideList, MileageList


class SearchForm(forms.Form):
    pass


class NewRideForm(forms.ModelForm):
    class Meta:
        model = RideList
        exclude = ('order', 'created_at', 'delivered', 'delivered_at')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 2, 'cols': 30}),
        }


class NewMileageForm(forms.ModelForm):
    class Meta:
        model = MileageList
        exclude = ('km_start', 'consumption', 'km_amount')
        widgets = {
            'created_at': forms.DateInput(attrs={'type': 'date'}, format='%d.%m.%Y')
        }

    def __init__(self, *args, **kwargs):
        super(NewMileageForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

transportapp/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from .forms import NewRideForm, NewMileageForm
from .models import RideList, MileageList, CarList


@login_required
def get_ride_list(request):
    objects = RideList.objects.all()
    paginator = Paginator(objects, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'objects': page_obj,
        'title': 'Поездки',
    }
    return render(request, 'transportapp/index.html', context)


class RideActiveListView(LoginRequiredMixin, ListView):
    """ Общий вывод активных поездок """
    model = RideList
    template_name = 'transportapp/index.html'
    context_object_name = 'objects'
    paginate_by = 20

    def get_queryset(self):
        return RideList.objects.filter(delivered=False)

    def get_context_data(self, **kwargs):
        context = super(RideActiveListView, self).get_context_data(**kwargs)
        context['title'] = 'Поездки в работе'
        return context


class RideCreateView(LoginRequiredMixin, CreateView):
    model = RideList
    template_name = 'transportapp/ride_crud_form.html'
    form_class = NewRideForm

    def get_context_data(self, **kwargs):
        context = super(RideCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Новая поездка'
        return context


@login_required
def set_delivered(request, pk):
    ride = get_object_or_404(RideList, pk=pk)
    if request.method == 'GET':
        if ride.delivered:
            ride.delivered = False
        else:
            ride.delivered = True
            ride.delivered_at = datetime.now()
        ride.save()

        return HttpResponseRedirect(
            reverse('transportapp:index')
        )


@login_required
def ride_delete(request, pk):
    ride = get_object_or_404(RideList, pk=pk)
    if request.method == 'GET':
        ride.delete()
        return HttpResponseRedirect(
            reverse('transportapp:index')
        )


class MileageListView(LoginRequiredMixin, ListView):
    model = MileageList
    template_name = 'transportapp/mileage.html'
    context_object_name = 'objects'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(MileageListView, self).get_context_data(**kwargs)
        context['title'] = 'Записи пробегов'
        context['cars'] = CarList.objects.all()
        return context


class MileageCreateView(LoginRequiredMixin, CreateView):
    model = MileageList
    template_name = 'transportapp/ride_crud_form.html'
    form_class = NewMileageForm

    def get_context_data(self, **kwargs):
        context = super(MileageCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Новая запись пробега'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        car = form.instance.car
        km_start = form.instance.car.km_real
        km_end = form.instance.km_end
        self.object.km_start = km_start
        self.object.km_amount = km_end - km_start
        self.object.consumption = (car.consumption * self.object.km_docs) / 100
        self.object.save()
        car.km_real = km_end
        car.km_docs = car.km_docs + form.instance.km_docs
        car.save()

        return HttpResponseRedirect(reverse('transportapp:mileage_list'))


def delete_mileage(request, pk):
    post = get_object_or_404(MileageList, pk=pk)
    car = post.car

    car.km_docs = car.km_docs - post.km_docs
    car.km_real = post.km_start

    car.save()
    post.delete()

    return HttpResponseRedirect(reverse('transportapp:mileage_list'))

transportapp/templates/transportapp/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block content%}
<div class="container">
    <div>
        <h3>{{title}}</h3>
    </div>
</div>
<div class="container d-flex justify-content-between">
    <div>
        <a href="{% url 'transportapp:index' %}" class="btn btn-outline-dark mb-3">Все</a>
        <a href="{% url 'transportapp:active_rides' %}" class="btn btn-outline-success mb-3">Активные</a>
    </div>
    <div class="col-6">
        <form action="/transport/" method="post" class="col-auto mb-3">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" class="form-control"
                       placeholder="Введите" name="data_for_search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" value="OK">Поиск</button>
                </div>
            </div>
        </form>
    </div>
    <div>
        <a href="{% url 'transportapp:ride_create' %}" class="btn btn-outline-dark mb-3">
            <i class="bi bi-plus-lg"></i> Поездка
        </a>
        <a href="{% url 'transportapp:mileage_list' %}" class="btn btn-outline-dark mb-3">
             Пробеги
        </a>
    </div>
</div>
{% if objects %}
<table class="table">
    <thead>
        <tr>
            <th>Дата</th>
            <th>Цель</th>
            <th>Адрес</th>
            <th>Описание</th>
            <th>Статус</th>
        </tr>
    </thead>
    <tbody>
    {% for item in objects %}
    <tr>
        <td>
            {{ item.created_at|date:"d.m.Y" }}
        </td>
        <td>
            {{ item.title }} {{ item.order.partner.name}}
        </td>
        <td>
            <a href="https://yandex.ru/maps/?text={{item.address}}" class="link-dark" target="_blank">
                {{ item.address }} <i class="bi bi-box-arrow-up-right"></i>
            </a>
        </td>
        <td>
            {% if item.order %}
                <a href="{% url 'ordersapp:order_detail' item.order.pk %}" class="link-dark" target="_blank">Заказ № {{item.order.pk}}</a><br>
                {{ item.order.description }}
            {% else %}
                {{ item.description }}
            {% endif %}
        </td>
        <td>
            {% if not item.delivered %}
                <a href="{% url 'transportapp:ride_delivered' item.pk %}" class="link-success">Провести</a>
                | <a href="{% url 'transportapp:ride_delete' item.pk %}" class="link-danger">Удалить</a>
            {% else %}
                <span class="badge bg-success">Выполнено:</span><br><span style="font-size: 12px">{{item.delivered_at|date:"d.m.Y"}}</span>
            <a href="{% url 'transportapp:ride_delivered' item.pk %}" style="font-size: 12px; text-decoration: none; border-bottom: 1px dashed;">Снять</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<div>
    <nav aria-label="Navigation">
        <ul class="pagination">
            {% if objects.has_previous %}
                <li class="page-item">
                    <a href="?page=1" class="page-link link-dark">Первая</a>
                </li>
                <li>
                    <a href="?page={{ objects.previous_page_number }}" class="page-link link-dark">&laquo;</a>
                </li>
            {% endif %}

            {% for page in objects.paginator.page_range %}
                {% if objects.number == page %}
                    <li class="page-item active"><a class="page-link link-dark">{{page}}</a></li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{page}}" class="page-link link-dark">{{page}}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if objects.has_next %}
                <li class="page-item">
                    <a href="?page={{ objects.paginator.next_page_number }}" class="page-link link-dark">&raquo;</a>
                </li>
                <li>
                    <a href="?page={{ objects.paginator.num_pages }}" class="page-link link-dark">Последняя</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% else %}
Нет данных
{% endif %}
<div style="padding-bottom: 30px;"></div>
{% endblock %}

transportapp/templates/transportapp/mileage.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}

{% block content%}
<div class="container d-flex justify-content-between" style="padding-top: 10px;">
    <div>
        <h3>{{title}}</h3>
    </div>
    <div>
    <a href="{% url 'transportapp:mileage_create' %}" class="btn btn-outline-dark mb-3">
        <i class="bi bi-plus-lg"></i> Запись
    </a>
    </div>
</div>
{% if cars %}
<div class="container">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Название</th>
            <th>Гос номер</th>
            <th>Пробег ОДО</th>
            <th>Пробег ДОК</th>
        </tr>
        </thead>
        <tbody>
        {% for car in cars %}
        <tr>
            <td>{{car.name}}</td>
            <td>{{car.gis_num}}</td>
            <td>{{car.km_real}}</td>
            <td>{{car.km_docs}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% if objects %}
<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Дата</th>
                <th>Авто</th>
                <th>Пробег за день</th>
                <th>Пробег по докам</th>
                <th>Расход за день</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for object in objects %}
        <tr>
            <td>{{object.created_at}}</td>
            <td>{{object.car}}</td>
            <td>{{object.km_amount}}</td>
            <td>{{object.km_docs}}</td>
            <td>{{object.consumption}}</td>
            <td>
                <a href="{% url 'transportapp:mileage_delete' object.pk %}" class="ling-danger">Удалить</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <nav aria-label="Navigation">
        <ul class="pagination">
            {% if objects.has_previous %}
                <li class="page-item">
                    <a href="?page=1" class="page-link link-dark">Первая</a>
                </li>
                <li>
                    <a href="?page={{ objects.previous_page_number }}" class="page-link link-dark">&laquo;</a>
                </li>
            {% endif %}

            {% for page in objects.paginator.page_range %}
                {% if objects.number == page %}
                    <li class="page-item active"><a class="page-link link-dark">{{page}}</a></li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{page}}" class="page-link link-dark">{{page}}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if objects.has_next %}
                <li class="page-item">
                    <a href="?page={{ objects.paginator.next_page_number }}" class="page-link link-dark">&raquo;</a>
                </li>
                <li>
                    <a href="?page={{ objects.paginator.num_pages }}" class="page-link link-dark">Последняя</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{%else%}
<div class="container"><h4>Нет данных</h4></div>
{%endif%}
<div style="padding-bottom: 30px;"></div>
{% endblock %}

transportapp/templates/transportapp/ride_crud_form.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="container" style="padding-top: 20px; margin: 0 auto;">
    <div class="card mb-4" style="max-width: 300px; margin: 0 auto;">
        <div class="card-header">{{ title }}
        </div>
        <div class="card-body">
            <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="container d-flex justify-content-around">
                    <div>
                        <input type="submit" class="form-control btn btn-outline-dark" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}